services:
  - type: web
    name: till-api
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm run api
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: TILL_DEV_SIMULATE
        value: "0"
      - key: OG_CHAIN_ID
        value: "16661"
      - key: OG_RPC_URL
        value: https://evmrpc.0g.ai
      - key: OG_EXPLORER_URL
        value: https://chainscan.0g.ai
      - key: OG_ROUTER_URL
        value: https://router-api.0g.ai/v1
      - key: OG_TRUST_MODE
        value: private
      - key: OG_PREFERRED_POLICY_MODEL
        value: 0gm-1.0-35b-a3b
      - key: OG_PAYMENT_LAYER
        value: "0xA3b15Bd2aD18BFB6b5f92D8AA9F444Dd59d1cE32"
      - key: OG_STORAGE_INDEXER_URL
        value: https://indexer-storage-turbo.0g.ai
      - key: ERC8004_IDENTITY
        value: "0x8004A169FB4a3325136EB29fA0ceB6D2e539a432"
      - key: ERC8004_REPUTATION
        value: "0x8004BAa17C55a88189AE136b182e5fdA19dE9b63"
      - key: TILL_AGENT_NFT
        value: "0x730e7c02D1C238D98aD38AFED98a7CBA980901bF"
      - key: TILL_POLICY
        value: "0xBf05e322e3C3047089e9Dd9E10Bd8ee320149f7c"
      - key: TILL_VERIFIER
        value: "0x4C8bed5Ec7e1F0c0CC7a7Ef141370dd9f4e1A7f1"
      - key: TILL_VAULT
        value: "0x2eD09745E5Ca4BdeaBc93aB3aab65781B03Ed4cB"
      - key: TILL_JOB_ESCROW
        value: "0x1BB730Ff8A4Ff93dE9eDD54B178C0Bc9ddE99de9"
      - key: TILL_USDCE_MAX_ATOMIC
        value: "500000"
